// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/mystery-gifter-api/internal/domain (interfaces: GroupInviteRepository)
//
// Generated by this command:
//
//	mockgen -destination mock_domain/group_invite_repository.go . GroupInviteRepository
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"

	domain "github.com/waliqueiroz/mystery-gifter-api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGroupInviteRepository is a mock of GroupInviteRepository interface.
type MockGroupInviteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGroupInviteRepositoryMockRecorder
	isgomock struct{}
}

// MockGroupInviteRepositoryMockRecorder is the mock recorder for MockGroupInviteRepository.
type MockGroupInviteRepositoryMockRecorder struct {
	mock *MockGroupInviteRepository
}

// NewMockGroupInviteRepository creates a new mock instance.
func NewMockGroupInviteRepository(ctrl *gomock.Controller) *MockGroupInviteRepository {
	mock := &MockGroupInviteRepository{ctrl: ctrl}
	mock.recorder = &MockGroupInviteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupInviteRepository) EXPECT() *MockGroupInviteRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGroupInviteRepository) Create(ctx context.Context, groupInvite domain.GroupInvite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, groupInvite)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGroupInviteRepositoryMockRecorder) Create(ctx, groupInvite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGroupInviteRepository)(nil).Create), ctx, groupInvite)
}

// GetActiveByGroupID mocks base method.
func (m *MockGroupInviteRepository) GetActiveByGroupID(ctx context.Context, groupID string) (*domain.GroupInvite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByGroupID", ctx, groupID)
	ret0, _ := ret[0].(*domain.GroupInvite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByGroupID indicates an expected call of GetActiveByGroupID.
func (mr *MockGroupInviteRepositoryMockRecorder) GetActiveByGroupID(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByGroupID", reflect.TypeOf((*MockGroupInviteRepository)(nil).GetActiveByGroupID), ctx, groupID)
}

// GetByID mocks base method.
func (m *MockGroupInviteRepository) GetByID(ctx context.Context, id string) (*domain.GroupInvite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.GroupInvite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGroupInviteRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGroupInviteRepository)(nil).GetByID), ctx, id)
}
