// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/mystery-gifter-api/internal/application (interfaces: GroupInviteService)
//
// Generated by this command:
//
//	mockgen -destination mock_application/group_invite_service.go . GroupInviteService
//

// Package mock_application is a generated GoMock package.
package mock_application

import (
	context "context"
	reflect "reflect"

	domain "github.com/waliqueiroz/mystery-gifter-api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGroupInviteService is a mock of GroupInviteService interface.
type MockGroupInviteService struct {
	ctrl     *gomock.Controller
	recorder *MockGroupInviteServiceMockRecorder
	isgomock struct{}
}

// MockGroupInviteServiceMockRecorder is the mock recorder for MockGroupInviteService.
type MockGroupInviteServiceMockRecorder struct {
	mock *MockGroupInviteService
}

// NewMockGroupInviteService creates a new mock instance.
func NewMockGroupInviteService(ctrl *gomock.Controller) *MockGroupInviteService {
	mock := &MockGroupInviteService{ctrl: ctrl}
	mock.recorder = &MockGroupInviteServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupInviteService) EXPECT() *MockGroupInviteServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGroupInviteService) Create(ctx context.Context, groupID, requesterID string) (*domain.GroupInvite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, groupID, requesterID)
	ret0, _ := ret[0].(*domain.GroupInvite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockGroupInviteServiceMockRecorder) Create(ctx, groupID, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGroupInviteService)(nil).Create), ctx, groupID, requesterID)
}

// GetActive mocks base method.
func (m *MockGroupInviteService) GetActive(ctx context.Context, groupID, requesterID string) (*domain.GroupInvite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActive", ctx, groupID, requesterID)
	ret0, _ := ret[0].(*domain.GroupInvite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActive indicates an expected call of GetActive.
func (mr *MockGroupInviteServiceMockRecorder) GetActive(ctx, groupID, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActive", reflect.TypeOf((*MockGroupInviteService)(nil).GetActive), ctx, groupID, requesterID)
}

// JoinGroup mocks base method.
func (m *MockGroupInviteService) JoinGroup(ctx context.Context, inviteID, userID string) (*domain.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinGroup", ctx, inviteID, userID)
	ret0, _ := ret[0].(*domain.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JoinGroup indicates an expected call of JoinGroup.
func (mr *MockGroupInviteServiceMockRecorder) JoinGroup(ctx, inviteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinGroup", reflect.TypeOf((*MockGroupInviteService)(nil).JoinGroup), ctx, inviteID, userID)
}
